#!/usr/bin/env ruby
# frozen_string_literal: true

require 'diataxis'

begin
  Diataxis::CLI.run(ARGV)
rescue Diataxis::UsageError => e
  puts e.usage_message
  exit e.exit_code
rescue Diataxis::Error => e
  puts "Error: #{e.message}"
  exit 1
end
